"""
Write screened candidate rows to Google Sheets SCREEN tab.
Columns (1-indexed):
A=CandidateID, B=CandidateName, C=Email, D=CurrentJobTitle, E=Skills,
F=TargetRole, G=JobDescription, H=RequiredSkills, I=ScreenResult,
J=Recommendation, K=Strengths, L=Weakness, M=MissingSkills,
N=InterviewFocusAreas, O=HiringRisks, P=Summary, Q=FinalStatus,
R=Status, S=CalendarLinkSent, T=InterviewDatetime, U=VapiCallID,
V=InterviewScore, W=FinalDecision, X=CommsSent, Y=HumanApproval, Z=ZohoCandidateID
"""
import httpx
from config.settings import get_settings
from core.logging import get_logger

logger = get_logger("tools.sheets_writer")
_settings = get_settings()

SHEETS_API = "https://sheets.googleapis.com/v4/spreadsheets"


def _get_access_token() -> str:
    """Get OAuth2 access token from saved google_token.json (generated by setup_google_auth.py)."""
    import json, os
    from google.oauth2.credentials import Credentials
    from google.auth.transport.requests import Request

    token_path = _settings.google_token_path
    if not token_path or not os.path.exists(token_path):
        raise RuntimeError(
            f"Google token not found at '{token_path}'. "
            "Run setup_google_auth.py first."
        )

    with open(token_path) as f:
        token_data = json.load(f)

    creds = Credentials(
        token=token_data.get("token"),
        refresh_token=token_data.get("refresh_token"),
        token_uri=token_data.get("token_uri", "https://oauth2.googleapis.com/token"),
        client_id=token_data.get("client_id"),
        client_secret=token_data.get("client_secret"),
        scopes=token_data.get("scopes"),
    )
    if creds.expired and creds.refresh_token:
        creds.refresh(Request())
    return creds.token


def _candidate_to_row(result: dict) -> list:
    """Map screening result dict → ordered list matching SCREEN tab columns A-Z."""
    return [
        result.get("candidate_id", ""),           # A - CandidateID
        result.get("candidate_name", ""),          # B - CandidateName
        result.get("email", ""),                   # C - Email
        result.get("current_job_title", ""),       # D - CurrentJobTitle
        result.get("skills", ""),                  # E - Skills
        result.get("target_role", ""),             # F - TargetRole
        "",                                        # G - JobDescription (populated by cron)
        "",                                        # H - RequiredSkills (populated by cron)
        result.get("screen_result", ""),           # I - ScreenResult (score)
        result.get("recommendation", ""),          # J - Recommendation
        result.get("strengths", ""),               # K - Strengths
        result.get("weaknesses", ""),              # L - Weakness
        result.get("missing_skills", ""),          # M - MissingSkills
        result.get("interview_focus_areas", ""),   # N - InterviewFocusAreas
        result.get("hiring_risks", ""),            # O - HiringRisks
        result.get("summary", ""),                 # P - Summary
        "",                                        # Q - FinalStatus
        "SCREENED",                                # R - Status
        "",                                        # S - CalendarLinkSent
        "",                                        # T - InterviewDatetime
        "",                                        # U - VapiCallID
        "",                                        # V - InterviewScore
        "",                                        # W - FinalDecision
        "",                                        # X - CommsSent
        "",                                        # Y - HumanApproval
        result.get("zoho_candidate_id", ""),       # Z - ZohoCandidateID
    ]


def append_screened_candidate(result: dict) -> int:
    """
    Append one screened candidate row to the SCREEN tab.
    Returns the row number written (1-indexed).
    """
    sheet_id = _settings.google_sheets_id
    if not sheet_id:
        raise RuntimeError("GOOGLE_SHEETS_ID not set in environment.")

    token = _get_access_token()
    row = _candidate_to_row(result)

    url = f"{SHEETS_API}/{sheet_id}/values/SCREEN!A:Z:append"
    params = {
        "valueInputOption": "USER_ENTERED",
        "insertDataOption": "INSERT_ROWS",
    }
    headers = {"Authorization": f"Bearer {token}"}
    body = {"values": [row]}

    resp = httpx.post(url, params=params, headers=headers, json=body, timeout=15)
    resp.raise_for_status()

    data = resp.json()
    updated_range = data.get("updates", {}).get("updatedRange", "")
    logger.info("sheet_row_written", range=updated_range, candidate=result.get("candidate_name"))

    # Parse row number from range like "SCREEN!A103:Z103"
    try:
        row_num = int(updated_range.split("!")[1].split(":")[0][1:])
    except Exception:
        row_num = -1

    return row_num


def update_human_approval(row_number: int, approved: bool) -> None:
    """Set col Y (HumanApproval) on a specific row."""
    sheet_id = _settings.google_sheets_id
    token = _get_access_token()

    value = "APPROVED" if approved else "REJECTED"
    range_name = f"SCREEN!Y{row_number}"
    url = f"{SHEETS_API}/{sheet_id}/values/{range_name}"
    params = {"valueInputOption": "USER_ENTERED"}
    headers = {"Authorization": f"Bearer {token}"}
    body = {"values": [[value]]}

    resp = httpx.put(url, params=params, headers=headers, json=body, timeout=15)
    resp.raise_for_status()
    logger.info("human_approval_written", row=row_number, value=value)
