"""
Write screened candidate rows to Google Sheets SCREEN tab.
Columns (1-indexed):
A=CandidateID, B=CandidateName, C=Email, D=CurrentJobTitle, E=Skills,
F=TargetRole, G=JobDescription, H=RequiredSkills, I=ScreenResult,
J=Recommendation, K=Strengths, L=Weakness, M=MissingSkills,
N=InterviewFocusAreas, O=HiringRisks, P=Summary, Q=FinalStatus,
R=Status, S=CalendarLinkSent, T=InterviewDatetime, U=VapiCallID,
V=InterviewScore, W=FinalDecision, X=CommsSent, Y=HumanApproval, Z=ZohoCandidateID
"""
import httpx
from config.settings import get_settings
from core.logging import get_logger

logger = get_logger("tools.sheets_writer")
_settings = get_settings()

SHEETS_API = "https://sheets.googleapis.com/v4/spreadsheets"


def _get_access_token() -> str:
    """Get OAuth2 access token from saved google_token.json (generated by setup_google_auth.py)."""
    import json, os
    from google.oauth2.credentials import Credentials
    from google.auth.transport.requests import Request

    token_path = _settings.google_token_path
    if not token_path or not os.path.exists(token_path):
        raise RuntimeError(
            f"Google token not found at '{token_path}'. "
            "Run setup_google_auth.py first."
        )

    with open(token_path) as f:
        token_data = json.load(f)

    creds = Credentials(
        token=token_data.get("token"),
        refresh_token=token_data.get("refresh_token"),
        token_uri=token_data.get("token_uri", "https://oauth2.googleapis.com/token"),
        client_id=token_data.get("client_id"),
        client_secret=token_data.get("client_secret"),
        scopes=token_data.get("scopes"),
    )
    if creds.expired and creds.refresh_token:
        creds.refresh(Request())
    return creds.token


def _candidate_to_row(result: dict, status: str = "SCREENED") -> list:
    """Map screening result dict → ordered list matching SCREEN/REJECTED tab columns A-Z."""
    return [
        result.get("candidate_id", ""),           # A - CandidateID
        result.get("candidate_name", ""),          # B - CandidateName
        result.get("email", ""),                   # C - Email
        result.get("current_job_title", ""),       # D - CurrentJobTitle
        result.get("skills", ""),                  # E - Skills
        result.get("target_role", ""),             # F - TargetRole
        "",                                        # G - JobDescription
        "",                                        # H - RequiredSkills
        result.get("screen_result", ""),           # I - ScreenResult (score)
        result.get("recommendation", ""),          # J - Recommendation
        result.get("strengths", ""),               # K - Strengths
        result.get("weaknesses", ""),              # L - Weakness
        result.get("missing_skills", ""),          # M - MissingSkills
        result.get("interview_focus_areas", ""),   # N - InterviewFocusAreas
        result.get("hiring_risks", ""),            # O - HiringRisks
        result.get("summary", ""),                 # P - Summary
        "",                                        # Q - FinalStatus
        status,                                    # R - Status
        "",                                        # S - CalendarLinkSent
        "",                                        # T - InterviewDatetime
        "",                                        # U - VapiCallID
        "",                                        # V - InterviewScore
        "",                                        # W - FinalDecision
        "",                                        # X - CommsSent
        "",                                        # Y - HumanApproval
        result.get("zoho_candidate_id", ""),       # Z - ZohoCandidateID
    ]


def _append_to_tab(tab: str, row: list, token: str) -> int:
    """Append a row to any tab. Returns the row number written."""
    sheet_id = _settings.google_sheets_id
    url = f"{SHEETS_API}/{sheet_id}/values/{tab}!A:Z:append"
    params = {"valueInputOption": "USER_ENTERED", "insertDataOption": "INSERT_ROWS"}
    headers = {"Authorization": f"Bearer {token}"}
    body = {"values": [row]}

    resp = httpx.post(url, params=params, headers=headers, json=body, timeout=15)
    resp.raise_for_status()

    updated_range = resp.json().get("updates", {}).get("updatedRange", "")
    logger.info("sheet_row_written", tab=tab, range=updated_range)

    try:
        return int(updated_range.split("!")[1].split(":")[0][1:])
    except Exception:
        return -1


def append_screened_candidate(result: dict) -> int:
    """
    Route candidate to the correct tab:
      - 'Do Not Advance' → REJECTED tab, status = REJECTED
      - Everything else  → SCREEN tab,   status = SCREENED
    Returns the row number written.
    """
    sheet_id = _settings.google_sheets_id
    if not sheet_id:
        raise RuntimeError("GOOGLE_SHEETS_ID not set in environment.")

    token = _get_access_token()
    is_rejected = (result.get("recommendation", "").lower() == "do not advance")

    if is_rejected:
        row = _candidate_to_row(result, status="REJECTED")
        row_num = _append_to_tab("REJECTED", row, token)
        logger.info("candidate_routed_rejected", candidate=result.get("candidate_name"))
    else:
        row = _candidate_to_row(result, status="SCREENED")
        row_num = _append_to_tab("SCREEN", row, token)
        logger.info("candidate_routed_screen", candidate=result.get("candidate_name"))

    return row_num


def reject_screened_candidate(screen_row_number: int, result: dict) -> None:
    """
    HR manually rejects a SCREENED candidate:
    1. Update col R on SCREEN tab to REJECTED + col Y to REJECTED
    2. Append the candidate row to REJECTED tab
    """
    sheet_id = _settings.google_sheets_id
    token = _get_access_token()

    # Mark SCREEN row as REJECTED (cols R + Y)
    range_name = f"SCREEN!R{screen_row_number}:Y{screen_row_number}"
    url = f"{SHEETS_API}/{sheet_id}/values/{range_name}"
    params = {"valueInputOption": "USER_ENTERED"}
    headers = {"Authorization": f"Bearer {token}"}
    # R is col 18, Y is col 25 — fill the gap cols S-X with empty strings
    body = {"values": [["REJECTED", "", "", "", "", "", "", "REJECTED"]]}

    resp = httpx.put(url, params=params, headers=headers, json=body, timeout=15)
    resp.raise_for_status()

    # Append to REJECTED tab
    row = _candidate_to_row(result, status="REJECTED")
    _append_to_tab("REJECTED", row, token)
    logger.info("candidate_moved_to_rejected", screen_row=screen_row_number,
                candidate=result.get("candidate_name"))


def update_human_approval(row_number: int, approved: bool, result: dict = None) -> None:
    """
    Approve: set col Y = APPROVED on SCREEN tab.
    Reject:  call reject_screened_candidate (marks SCREEN + copies to REJECTED tab).
    """
    if approved:
        sheet_id = _settings.google_sheets_id
        token = _get_access_token()
        url = f"{SHEETS_API}/{sheet_id}/values/SCREEN!Y{row_number}"
        params = {"valueInputOption": "USER_ENTERED"}
        headers = {"Authorization": f"Bearer {token}"}
        body = {"values": [["APPROVED"]]}
        resp = httpx.put(url, params=params, headers=headers, json=body, timeout=15)
        resp.raise_for_status()
        logger.info("human_approval_written", row=row_number, value="APPROVED")
    else:
        if result is None:
            # Fallback: just mark col Y on SCREEN tab
            sheet_id = _settings.google_sheets_id
            token = _get_access_token()
            url = f"{SHEETS_API}/{sheet_id}/values/SCREEN!Y{row_number}"
            params = {"valueInputOption": "USER_ENTERED"}
            headers = {"Authorization": f"Bearer {token}"}
            body = {"values": [["REJECTED"]]}
            resp = httpx.put(url, params=params, headers=headers, json=body, timeout=15)
            resp.raise_for_status()
        else:
            reject_screened_candidate(row_number, result)
